version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - .volumes/mongo-data:/data/db
      - ./sampleDB:/sampleDB
      - ./docker-entrypoint-initdb.d/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    environment:
      MONGO_INITDB_DATABASE: "agregate"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file: .env
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  mongo-data:

networks:
  default:
    name: mongodb_network